### ISSUE TITLE
not well-formed (invalid token)

### ISSUE THREAD

**Issue by davidem** [TheGroundZero/openvasreporting#10]
Good afternoon, 

I stumbled on the following error, not sure what's causing it: 

`kali:~/Downloads/openvasreporting$ python3 -m openvasreporting -i report.xml -f xlsx
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/Downloads/openvasreporting/openvasreporting/__main__.py", line 17, in <module>
    main()
  File "/home/user/Downloads/openvasreporting/openvasreporting/openvasreporting.py", line 33, in main
    convert(config)
  File "/home/user/Downloads/openvasreporting/openvasreporting/openvasreporting.py", line 87, in convert
    openvas_info = openvas_parser(config.input_files, config.min_level)
  File "/home/user/Downloads/openvasreporting/openvasreporting/libs/parser.py", line 58, in openvas_parser
    root = Et.parse(f_file).getroot()
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 35, column 1349`

I looked in my xml-report, but on line 35 column 1349 is an "n". Any clue?

Report came from GVM virtual appliance running Greenbone OS 6.0.0. Played around with utf-8 and BOM, but that didn't help. 

Cheers and thanks,

David

**Comment by davidem** [comment]
Figured this error out. The xml file from OpenVAS had several '&' characters which were not encoded for XML, like this: '&amp;'. After replacing al &'s, I'm left with the same error as 'beercity' (#9).

**Comment by TheGroundZero** [comment]
Looks like an encoding issue on OpenVAS'/Greenbone's side then.
Perhaps notify them as well.

**Comment by davidem** [comment]
Yep, I've put that on my todolist for today ;)
