### ISSUE TITLE
"--template openvasreporting/src/openvas-template.docx" is forced regardless of "--format xlsx" argument

### ISSUE THREAD

**Issue by dstidham617** [TheGroundZero/openvasreporting#3]
Using `--format xlsx` returns this error:

```
Traceback (most recent call last):
  File "./server.py", line 78, in <module>
    main()
  File "./server.py", line 33, in main
    setup_socket(args.ip, args.port, args.format)
  File "./server.py", line 62, in setup_socket
    openvasreporting.convert(config)
  File "/usr/local/lib/python3.7/site-packages/openvasreporting/openvasreporting.py", line 88, in convert
    exporters()[config.filetype](openvas_info, config.template, config.output_file)
  File "/usr/local/lib/python3.7/site-packages/openvasreporting/libs/export.py", line 59, in export_to_excel
    raise NotImplementedError("Use of template is not supported in XSLX-output.")
NotImplementedError: Use of template is not supported in XSLX-output.
```

Not sure how to fix this one. Maybe a separate `convert_docx` function if you want docx format?

**Comment by TheGroundZero** [comment]
Will continue this in #2
