### ISSUE TITLE
Reporting does not work with GVM21 

### ISSUE THREAD

**Issue by Rdago** [TheGroundZero/openvasreporting#35]
Hello @TheGroundZero 

since we updated our GVM to Version 21.4.5 the openvasreporting tool does not work anymore giving us this error message: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gvmreport/openvasreporting/openvasreporting/__main__.py", line 19, in <module>
    main()
  File "/home/gvmreport/openvasreporting/openvasreporting/openvasreporting.py", line 83, in main
    convert(config)
  File "/home/gvmreport/openvasreporting/openvasreporting/openvasreporting.py", line 102, in convert
    openvas_info = parsers()[config.report_type](config)
  File "/home/gvmreport/openvasreporting/openvasreporting/libs/parser.py", line 62, in openvas_parser_by_vuln
    raise IOError("Invalid report format")
OSError: Invalid report format
```

There might have been a change in xml parsing in newer version.

**Comment by iman4000** [comment]
@Rdago did you find the solution?

I have the same problem now

**Comment by iman4000** [comment]
@Rdago @TheGroundZero did you find the solution?

I have the same problem now

**Comment by TheGroundZero** [comment]
@iman4000 
This project hasn't been updated in a while and I haven't kept track of changes in OpenVAS since it got incorporated into Greenbone. As such it's very likely that there have been breaking changes in the XML output.

**Comment by iman4000** [comment]
@TheGroundZero 
Thanks for your answering! since you are working into Greenbone, can you give me an example for getting csv format report with gvm-tools? i did search and only found xml format examples!
